export class Sitio{
    constructor(
        public _id:string,
        public date:any,
        public image:any,
        public numero_caso: String,
        public nombre_sitio: String,
        public clave_sitio: String,
        public clave_norm: any,
        public clave_antigua: String,
        public cod_ucr: String,
  
        public estudio_impacto_ambiental: Boolean,
        public monitoreo_mov_tierras: Boolean,
        public evaluacion: Boolean,
        public peritaje: Boolean,
        public excavacion_aislada: Boolean,
        public rescate: Boolean,
        public inspeccion: Boolean,
        public trabajo_graduacion: Boolean,
        public regional: Boolean,
        public subregional:Boolean,
        public tipo_proyecto: String,
        public abrigo_cueva_caverna: Boolean,
        public arquitectonico: Boolean,
        public basurero: Boolean,
        public camino: Boolean,
        public conchero: Boolean,
        public funerario: Boolean,
        public habitacion: Boolean,
        public materiales_dispersos: Boolean,
        public petroglifo: Boolean,
        public salina: Boolean,
        public taller: Boolean,
        public tipo_monumento: String,
        public registrador: String,
        public consultoria: Boolean,
        public fundacion: Boolean,
        public ice: Boolean,
        public literatura: Boolean,
        public mncr: Boolean,
        public parques_nacionales: Boolean,
        public ucr: Boolean,
        public institucion: String,
        public hallazgo: String,
        public fecha_registro: string,
        public links: any,
        public provincia: String,
        public canton: String,
        public distrito: String,
        public region: String,
        public altitud: String,
        public excavacion: Boolean,
        public arbitratia: Boolean,
        public probabilistico: Boolean,
        public horizontal: Boolean,
        public sondeo: Boolean,
        public trinchera: Boolean,
        public ceramica: Boolean,
        public litica: Boolean,
        public tierra: Boolean,
        public carbon: Boolean,
        public fauna: Boolean,
        public flora: Boolean,
        public oro: Boolean,
        public jade: Boolean,
        public cobre: Boolean,
        public vidrio: Boolean,
        public porcelana: Boolean,
        public hierro: Boolean,
        public lapidaria: Boolean,
        public esferas: Boolean,
        public pisos: Boolean,
        public tesis: Boolean,
        public monografia: Boolean,
        public publicacion: Boolean,
        public titulo: String,
        public artefactos: Boolean,
        public croquis: Boolean,
        public planos: Boolean,
        public dibujos: Boolean,
        public video: Boolean,
        public latitude: number,
        public Logitude: number,
        public longitude: number,
        public coordenadas: String,
        public google: String,
        public id_google: String,
        public coordenadas_google: String,
        public num_consecutivo: String,
        public reportes: String,
        public direccion: String,
        public huaqueado: Boolean,
        public sembrado: Boolean,
        public hoja_cartografica: String,
        public lambert_oe: String,
        public lambert_ns: String,
        public grad_lat: String,
        public min_lat: String,
        public seg_lat: String,
        public grad_long: String,
        public min_long: String,
        public seg_log: String,
        public localizacion_gps: Boolean,
        public area_estimada: String,
        public zona_vida: String,   
        public mil_dos_ocho_mi_ac: Boolean,
        public coordenada_convert: String,
        public ocho_mil_cuatro_mil_ac: Boolean,
        public diezmil_ochomil_ac: Boolean,
        public cuatro_mil_mil_quinientos_ac: Boolean,
        public mil_quinientos_quinientos_ac: Boolean,
        public crtm05_e: Number,
        public quinientos_trecientos_dc: Boolean,
        public trescientos_ochocientos_dc: Boolean,
        public ochocientos_mil_tres_cincuenta_dc: Boolean,
        public mil_tres_cincuenta_mil_quinientos_dc: Boolean,
        public mil_quinientos_mil_ochocientos_dc: Boolean,
        public mil_ochocientos_mil_novecientos_sc: Boolean,
        public periodo:String,
        public lev_cartografico: Boolean,
        public rec_superficie: Boolean,
        public cala_estratatigrafica: Boolean,
        public limpieza_perfiles: Boolean,
        public limpieza_razgos: Boolean,
        public huesos_humanos: Boolean,
        public madera_fibra: Boolean,
        public arcilla_cocida: Boolean,
        public litica_dat: Boolean,
        public ceramica_dat: Boolean,
        public radiocarbono_dat: Boolean,
        public hoja_registro: Boolean,
        public material_fotografico: Boolean,
        public id_google_comillas: String,
        public diarios_campo: Boolean,
        public documento_kml: String,
        public nombre_sitio_google: String,
        public crtm05_n: Number,
        public rio_cercano: String,
        public levantamiento_cartografico: String,
        public fase_9: String,
        public arado: Boolean,
        public bibliografia: String,
        public biodeterioro: Boolean,
        public catalogo_sitios_ucr: Boolean,
        public causa_penal: String,
        public trabajo_campo: String,
        public recoleccion: String,
        public excava:String,
        public material_grafico: String,
        public composicion_cronologica: String,
        public concha: Boolean,
        public construccion: Boolean,
        public erosion: Boolean,
        public estado_conservacion: any,
        public estatuaria: Boolean,
        public expediente_setena: String,
        public fase_1: String,
        public fase_2: String,
        public fase_3: String,
        public fase_4: String,
        public fase_5: String,
        public fase_6: String,
        public fase_7: String,
        public fase_8: String,
        public fase_10: String,
        public fecha_digitacion: String,
        public investigador: String,
        public loza: Boolean,
        public mecanizado: Boolean,
        public meteorizacion: Boolean,
        public no_perturbado: Boolean,
        public otra: String,
        public otro: String,
        public otro_m: String,
        public otro_r: String,
        public otro_rec_superficie: String,
        public otr_tc: String,
        public otro_tipo_proyecto: String,
        public otro_ts: String,
        public otros: String,
        public otros_da: String,
        public paisajes_culturales_sumergidos: Boolean,
        public pastoreo: Boolean,
        public materiales_recuperados: any,
        public registro_numero: String,
        public plano_catrasto: String,
        public profundidad_depositos: String,
        public rec_propiedad: Boolean,
        public registro_fotografico: Boolean,
        public reserva_arqueologica: Boolean,
        public resina: Boolean,
        public restos_barcos: Boolean,
        public ruinas_asentamientos: Boolean,
        public territorio_indigena: Boolean,
        public patrimonio_acuatico: any,
        public vestigios_cavernas: Boolean,
        public fechamiento_adiometrico: String,
        public sitios_marina: Boolean,
        public informe: Boolean,
        public doc_tipo_info: String,
        public doc_ubicacion: String,
        public doc_autor: String,
        public doc_titulo: String,
        public doc_numero: String,
        public doc_contenido: String,
        public doc_observaciones: String,
        public doc_web: String,
        public doc_fecha_digita: String,
        public doc_descripcion_material: String,
        public doc_cantidad: number,
        public x: number,
        public y: number,
        // ✅ SIGMA (Información general)
  public descripcion_del_monumento?: string,
  public banco_unificado?: number | string,
  public area_estimada_del_monumento_m2?: number | string,
  public reserva_arqueologica_m2?: number | string,
  public persona_investigadora?: string,
 

  public consecutivo_informes?: number | string,
  public consecutivo_diarios_campo?: number | string,
  public consecutivo_mapas?: number | string,
  public observaciones?: string,
  // ✅ SIGMA - Tab Registro (opcional)
public persona_registradora?: string,
public fecha_de_registro?: string, // o Date si lo manejas como Date

public denuncia?: boolean,
public reporte?: boolean,
public proyecto_investigacion?: boolean,
public nombre_proyecto?: string,

public fundacion_anastasio_alfaro?: boolean,
public otra_institucion?: string,
// ✅ TAB Localización (SIGMA)
public direccion_del_monumento?: string,
public distancia_carretera_principal?: number | string,
public plano_catastro?: string,
public area_conservacion?: string,
public area_silvestre_protegida?: string,
public distancia_rio?: number | string,
public quebrada_cercana?: string,
public distancia_quebrada?: number | string,
public altitud_msnm?: number | string,
// TAB 3 - Localización / Contacto (SIGMA)
// Contacto
public propietario?: string,
public telefono_propietario?: string,
public correo_propietario?: string,
public arrendatario?: string,
public telefono_arrendatario?: string,
public correo_arrendatario?: string,
public informante?: string,
public telefono_informante?: string,
public correo_informante?: string,
// --- TAB Tipo de sitio (SIGMA) ---
public terrestre?: boolean,

public patrimonio_cultural_subacuatico?: boolean,
public taller_litico?: boolean,
// Tipo de patrimonio sumergido
public asentamientos_sumergidos?: boolean,

public pecios?: boolean,
public sitios_explotacion_marina?: boolean,
public trampa_pesca?: boolean,

// Texto libre
public otro_tipo_monumento?: string, // si lo vas a mostrar
public no_determinado?: boolean,     // si existe en tu data

// COMPONENTES
public unicomponente?: boolean,
public bicomponente?: boolean,
public multicomponente?: boolean,

// CRONOLOGÍA
public c12000_8000_ac?: boolean,
public c8000_4000_ac?: boolean,
public c4000_1500_ac?: boolean,
public c1500_300_ac?: boolean,
public c2000_500_ac?: boolean,
public c500_ac_300_dc?: boolean,
public c300_800_dc?: boolean,
public c800_1350_dc?: boolean,
public c1350_1550_dc?: boolean,
public c800_1550_dc?: boolean,
public c1550_1821_dc?: boolean,
public c1821_1950_dc?: boolean,
public otra_temporalidad?: string,

// DATACIÓN
public datacion_ceramica?: boolean,
public datacion_litica?: boolean,
public datacion_radiocarbono?: boolean,
public datacion_termoluminiscencia?: boolean,
public resultados_fechamientos?: string,
public otros_tipos_dataciones?: string,
// FASES
public orosi?: boolean,
public tempisque?: boolean,
public bagaces?: boolean,
public sapoa?: boolean,
public ometep?: boolean,
public la_montana?: boolean,
public el_bosque?: boolean,
public la_selva?: boolean,
public la_cabana?: boolean,
public barva?: boolean,
public pavas?: boolean,
public curridabat?: boolean,
public cartago?: boolean,
public ron_ron?: boolean,
public platanar?: boolean,
public venecia?: boolean,
public jaco?: boolean,
public los_suenos?: boolean,
public sinancra?: boolean,
public aguas_buenas?: boolean,
public chiriqui?: boolean,
public ometepe?: boolean,
public recoleccion_superficie?: boolean,
public recorrido_propiedad?: boolean,
public calco_petroglifo?: boolean,
public cala_estratigrafica?: boolean,
public limpieza_estructura?: boolean,
public sondeo_cateo?: boolean,
public prospeccion_asistematica?: boolean,
public prospeccion_sistematica?: boolean,
public recoleccion_arbitraria?: boolean,
public recoleccion_probabilistica?: boolean,
public bosquejo?: boolean,
public planimetrico?: boolean,
public topografico?: boolean,
public otra_clase_levantamiento?: string,
public descripcion_metodologica?: string,
public ecofacto?: boolean,
public teja?: boolean,
public artefacto_ceramico?: boolean,
public artefacto_metalico?: boolean,
public artefacto_litico?: boolean,
public artefacto_organico?: boolean,
public cobre_guanina_pirita?: boolean,
public espejos_de_pirita?: boolean,
public piedra_verde?: boolean,
public restos_humanos?: boolean,
public otros_materiales_excavados?: string,
public arte_rupestre?: boolean,
public estructura_funeraria?: boolean,
public estructura_habitacional?: boolean,
public estructura_vial?: boolean,
public estructura_demarcatoria?: boolean,
public pecto?: boolean,

public otra_evidencia_inmueble?: string,

// Estado de conservación
public perturbado?: boolean,

// Tipo de vegetación
public bosque?: boolean,
public cultivo_agricola?: boolean,
public matorral?: boolean,
public plantacion_forestal?: boolean,
public sin_vegetacion?: boolean,
public tacotal?: boolean,
public otra_vegetacion?: string,

// Cobertura espacial
public poco_denso?: boolean,
public semidenso?: boolean,
public denso?: boolean,
public muy_denso?: boolean,

// Pendiente
public plano?: boolean,
public poco_acentuado?: boolean,
public ligeramente_acentuado?: boolean,
public acentuado?: boolean,
public muy_acentuado?: boolean,

// Uso del suelo
public agricola?: boolean,
public area_protegida?: boolean,
public deportivo?: boolean,
public ganadero?: boolean,
public industrial?: boolean,
public minero?: boolean,
public portuario?: boolean,
public sin_uso?: boolean,
public silvicola?: boolean,
public turismo?: boolean,
public urbano?: boolean,
public otro_uso_suelo?: string,

    ){}
}